version: '3'

services:
  fast-api:
    container_name: "uvicorn"
    build: .
    hostname: "localhost"
    ports:
    - '8000:8000'
    networks:
      - proxy.front-network
    depends_on:
      - postgres

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_DB: "university"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    networks:
      - proxy.front-network

networks:
  proxy.front-network:
      driver: bridge